# from tools.excel_tools.config import path
# from tools.excel_tools.read_functions.read_trever_pairs import load_trever_pairs_from

TREVER_PAIRS = [
    '1INCH/EUR',
    'AAVE/EUR',
    'AMP/EUR',
    'ANT/EUR',
    'ATOM/EUR',
    'AXS/EUR',
    'BAL/EUR',
    'BAT/EUR',
    'BNB/EUR',
    'BNT/EUR',
    'CELO/EUR',
    'CHZ/EUR',
    'CLV/EUR',
    'CRV/EUR',
    'DYDX/EUR',
    'EGLD/EUR',
    'ENJ/EUR',
    'ETC/EUR',
    'FET/EUR',
    'FIL/EUR',
    'FLOW/EUR',
    'FTM/EUR',
    'GALA/EUR',
    'GNO/EUR',
    'GRT/EUR',
    'HBAR/EUR',
    'HOT/EUR',
    'IMX/EUR',
    'IOTX/EUR',
    'KNC/EUR',
    'LPT/EUR',
    'LRC/EUR',
    'MANA/EUR',
    'MKR/EUR',
    'NMR/EUR',
    'OCEAN/EUR',
    'OGN/EUR',
    'OMG/EUR',
    'OXT/EUR',
    'RAY/EUR',
    'REN/EUR',
    'SAND/EUR',
    'SHIB/EUR',
    'SNX/EUR',
    'SUSHI/EUR',
    'THETA/EUR',
    'UMA/EUR',
    'YFI/EUR',
]

# if __name__ == "__main__":
#     TREVER_PAIRS = load_trever_pairs_from(path)
#     pass